language: python
python:
  - '3.6'
before_install:
  - pip install pipenv
  - pip install codecov
install:
  - pipenv install

#script:
#  - pytest
#  - codecov
script:
  - coverage run pytest
#  - coverage run tests.py

after_success:
  - codecov